### PR TITLE
#44

### PR DESCRIPTION
**Pull request by Rhineheart**
Fixed issue #44

### CODE REVIEW

**Comment by Rhineheart** [comment]
Latest commit also addresses #33

**Comment by ixuz** [comment]
I've reviewed the pull request and added 2 comments.
I consider this pull request #44 up to commit df2f8f71ea01af225c7632cdc4e759eef18ea69d OK.

**Comment by Rhineheart** [comment]
We can of course break it out. Right now the code is filled to the brim with constants. Colors, offsets, etc. Create an issue.

**Comment by saikyun** [comment]
boom baby

**Pull request merged**
